name: Deploy site

on:
  push:
    branches:
      - main
    paths:
      - "site/**"
      - ".github/workflows/deploy.yml"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-central-1
  S3_BUCKET: secure-static-site-lexi
  CLOUDFRONT_DISTRIBUTION_ID: E1OAA0MZ7NQ46L

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          role-to-assume: arn:aws:iam::445567089145:role/SecureStaticSiteGitHubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync site to S3
        run: |
          aws s3 sync site/ "s3://${S3_BUCKET}/" \
            --delete \
            --sse aws:kms \
            --sse-kms-key-id alias/secure-static-site

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${CLOUDFRONT_DISTRIBUTION_ID}" \
            --paths "/*"
